import CryptoKit
import Foundation
import Testing

@testable import LPMVault

private let cryptoInteropPrincipalID = "00000000-0000-4000-8000-000000000002"

/// Tests that Swift VaultCrypto can decrypt data encrypted by Rust lpm-vault crypto.
/// Test vectors were generated by the Rust crate with known keys.
@Suite("Crypto Interop: Rust ↔ Swift")
struct CryptoInteropTests {

	// ── Test vectors generated by Rust lpm-vault ──

	// Bob's X25519 keypair (generated by Rust)
	let bobPrivateKey = "NqBDUXorl6QdGfKO71T7zs8EwpmJThEj9i6s95x3LnA="
	let bobPublicKey = "bZeps1e2E/303Ch3OcYWHkgsshIU66wRNzrhJbv9/1k="

	// Vault encrypted by Rust (AES-256-GCM)
	let encryptedBlob = "cXlerr85v3ArGvRP:i3xC4zrerSnq6eSXLzPawPlwkwi7i0G7LhFBDtRye3c7LUbaTulbe0RnV5Oc/cqiGOi+YkOKvK8KZlJ+2hzcVzy1LATgFS/6IW0Kq9OXFnb5zaJtXxBPZgFLLBo="

	// AES key wrapped for Bob using X25519 ECIES (by Rust)
	let wrappedKeyForBob = "qdGmOrhXlx0iWRywn5SR2dLyvlcXK47YkSwj6spIqBk=:yzl1/8jJoPcXeVGj:wVhLJAPgsdDNQpHU543nQ6G8Y7RhfKfoEsdFw8q/kCEC6pcA+vNz03Xtosx9hpqc"

	// Expected decrypted JSON
	let expectedJSON = #"{"environments":{"default":{"DB_HOST":"prod.db","API_KEY":"sk-secret-123"}}}"#

	// MARK: - Org Sync (X25519 ECIES)

	@Test("Swift unwraps Rust X25519-wrapped key and decrypts vault")
	func unwrapRustX25519Key() throws {
		let privKeyData = Data(base64Encoded: bobPrivateKey)!

		// Unwrap the AES key using Bob's private key
		let aesKey = try VaultCrypto.unwrapKeyFromSender(wrapped: wrappedKeyForBob, privateKey: privKeyData)

		// Decrypt the vault blob
		let plaintext = try VaultCrypto.decrypt(key: aesKey, encoded: encryptedBlob)
		let json = String(data: plaintext, encoding: .utf8)!

		#expect(json == expectedJSON)
	}

	@Test("Swift wraps key, Swift unwraps — round-trip")
	func swiftX25519RoundTrip() throws {
		let (privData, pubData) = VaultCrypto.generateX25519Keypair()
		let aesKey = VaultCrypto.generateAESKey()

		let wrapped = try VaultCrypto.wrapKeyForRecipient(aesKey: aesKey, recipientPublicKey: pubData)
		let unwrapped = try VaultCrypto.unwrapKeyFromSender(wrapped: wrapped, privateKey: privData)

		// Compare key bytes
		let originalBytes = aesKey.withUnsafeBytes { Data($0) }
		let unwrappedBytes = unwrapped.withUnsafeBytes { Data($0) }
		#expect(originalBytes == unwrappedBytes)
	}

	@Test("Wrong private key cannot unwrap")
	func wrongKeyFails() throws {
		let (_, otherPub) = VaultCrypto.generateX25519Keypair()
		let (wrongPriv, _) = VaultCrypto.generateX25519Keypair()
		let aesKey = VaultCrypto.generateAESKey()

		let wrapped = try VaultCrypto.wrapKeyForRecipient(aesKey: aesKey, recipientPublicKey: otherPub)
		#expect(throws: (any Error).self) {
			_ = try VaultCrypto.unwrapKeyFromSender(wrapped: wrapped, privateKey: wrongPriv)
		}
	}

	@Test("Non-contributory X25519 recipient keys are rejected")
	func nonContributoryRecipientFails() {
		#expect(throws: (any Error).self) {
			_ = try VaultCrypto.wrapKeyForRecipient(
				aesKey: VaultCrypto.generateAESKey(),
				recipientPublicKey: Data(repeating: 0, count: 32)
			)
		}
	}

	@Test("Non-contributory X25519 sender keys are rejected")
	func nonContributorySenderFails() {
		let zeroKey = Data(repeating: 0, count: 32).base64EncodedString()
		let wrapped = "\(zeroKey):\(Data(repeating: 0, count: 12).base64EncodedString()):\(Data(repeating: 0, count: 48).base64EncodedString())"
		let (privateKey, _) = VaultCrypto.generateX25519Keypair()

		#expect(throws: (any Error).self) {
			_ = try VaultCrypto.unwrapKeyFromSender(wrapped: wrapped, privateKey: privateKey)
		}
	}

	@Test("Cross-user: Swift encrypts for Rust-generated public key")
	func swiftEncryptsForRustKey() throws {
		let bobPubData = Data(base64Encoded: bobPublicKey)!
		let bobPrivData = Data(base64Encoded: bobPrivateKey)!

		// Swift encrypts a vault and wraps for Bob (Rust-generated key)
		let secrets = #"{"test":"swift-to-rust"}"#
		let aesKey = VaultCrypto.generateAESKey()
		let blob = try VaultCrypto.encrypt(key: aesKey, plaintext: Data(secrets.utf8))
		let wrapped = try VaultCrypto.wrapKeyForRecipient(aesKey: aesKey, recipientPublicKey: bobPubData)

		// Bob unwraps with his Rust-generated private key
		let unwrappedKey = try VaultCrypto.unwrapKeyFromSender(wrapped: wrapped, privateKey: bobPrivData)
		let decrypted = try VaultCrypto.decrypt(key: unwrappedKey, encoded: blob)
		let json = String(data: decrypted, encoding: .utf8)!

		#expect(json == secrets)
	}

	@Test("Public key derivation matches between Swift and Rust")
	func publicKeyDerivation() throws {
		let privData = Data(base64Encoded: bobPrivateKey)!
		let expectedPub = Data(base64Encoded: bobPublicKey)!

		let derivedPub = try VaultCrypto.x25519PublicFromPrivate(privData)
		#expect(derivedPub == expectedPub)
	}

	@Test("Different ephemeral key each wrap")
	func differentEphemeralEachTime() throws {
		let (_, pubData) = VaultCrypto.generateX25519Keypair()
		let aesKey = VaultCrypto.generateAESKey()

		let a = try VaultCrypto.wrapKeyForRecipient(aesKey: aesKey, recipientPublicKey: pubData)
		let b = try VaultCrypto.wrapKeyForRecipient(aesKey: aesKey, recipientPublicKey: pubData)
		#expect(a != b)
	}

	@Test("AES-GCM wire format round-trips every Base64 boundary")
	func aesGCMWireFormatBoundaries() throws {
		let key = VaultCrypto.generateAESKey()
		for length in [0, 1, 2, 3, 11, 12, 13, 15, 16, 17, 1_023, 1_024, 1_025] {
			let plaintext = Data((0..<length).map { UInt8(truncatingIfNeeded: $0) })
			let encoded = try VaultCrypto.encrypt(key: key, plaintext: plaintext)
			let parts = encoded.split(separator: ":", maxSplits: 1)

			#expect(parts.count == 2)
			#expect(Data(base64Encoded: String(parts[0]))?.count == 12)
			#expect(Data(base64Encoded: String(parts[1]))?.count == length + 16)
			#expect(try VaultCrypto.decrypt(key: key, encoded: encoded) == plaintext)
		}
	}

	@Test("Protocol v3 AAD matches the cross-language organization vector")
	func protocolV3AADInteropVector() throws {
		let aad = try VaultCrypto.syncAssociatedData(
			scope: .organization(slug: "acme"),
			principalId: cryptoInteropPrincipalID,
			vaultId: "vault-123",
			revision: 42,
			cryptoVersion: 3
		)

		#expect(aad.map { String(format: "%02x", $0) }.joined()
			== "6c706d2d7661756c742d73796e630000000003020000002430303030303030302d303030302d343030302d383030302d303030303030303030303032000000097661756c742d3132330000000461636d65000000000000002a")
	}

	@Test("Protocol v3 rejects a payload copied to another vault ID")
	func protocolV3RejectsCrossVaultSubstitution() throws {
		let key = VaultCrypto.generateAESKey()
		let encrypted = try VaultCrypto.encryptPayload(
			key: key,
			plaintext: Data(#"{"TOKEN":"secret"}"#.utf8),
			scope: .personal,
			principalId: cryptoInteropPrincipalID,
			vaultId: "vault-a",
			revision: 1
		)

		#expect(throws: (any Error).self) {
			_ = try VaultCrypto.decryptPayload(
				key: key,
				encoded: encrypted,
				scope: .personal,
				principalId: cryptoInteropPrincipalID,
				vaultId: "vault-b",
				revision: 1,
				cryptoVersion: VaultCrypto.currentCryptoVersion
			)
		}
	}

	@Test("Protocol v3 rejects a payload copied to another principal")
	func protocolV3RejectsCrossPrincipalSubstitution() throws {
		let key = VaultCrypto.generateAESKey()
		let encrypted = try VaultCrypto.encryptPayload(
			key: key,
			plaintext: Data(#"{"TOKEN":"secret"}"#.utf8),
			scope: .personal,
			principalId: cryptoInteropPrincipalID,
			vaultId: "vault-a",
			revision: 1
		)

		#expect(throws: (any Error).self) {
			_ = try VaultCrypto.decryptPayload(
				key: key,
				encoded: encrypted,
				scope: .personal,
				principalId: "00000000-0000-4000-8000-000000000456",
				vaultId: "vault-a",
				revision: 1,
				cryptoVersion: VaultCrypto.currentCryptoVersion
			)
		}
	}

	@Test("Same-vault ciphertext cannot be replayed under a newer revision")
	func sameVaultCiphertextReplayIsRejected() throws {
		let key = VaultCrypto.generateAESKey()
		let encryptedAtRevisionOne = try VaultCrypto.encryptPayload(
			key: key,
			plaintext: Data(#"{"TOKEN":"old"}"#.utf8),
			scope: .personal,
			principalId: cryptoInteropPrincipalID,
			vaultId: "vault-a",
			revision: 1
		)

		#expect(throws: (any Error).self) {
			_ = try VaultCrypto.decryptPayload(
				key: key,
				encoded: encryptedAtRevisionOne,
				scope: .personal,
				principalId: cryptoInteropPrincipalID,
				vaultId: "vault-a",
				revision: 2,
				cryptoVersion: VaultCrypto.currentCryptoVersion
			)
		}
	}

	@Test("Protocol v3 rejects payloads wrapped with a different account key")
	func protocolV3RejectsWrongWrappingKey() throws {
		let aesKey = VaultCrypto.generateAESKey()
		let encrypted = try VaultCrypto.encryptPayload(
			key: aesKey,
			plaintext: Data(#"{"TOKEN":"attacker-controlled"}"#.utf8),
			scope: .personal,
			principalId: cryptoInteropPrincipalID,
			vaultId: "vault-a",
			revision: 1
		)
		let wrapped = try VaultCrypto.wrapKey(
			wrappingKey: VaultCrypto.generateAESKey(),
			aesKey: aesKey
		)

		#expect(throws: (any Error).self) {
			_ = try VaultCrypto.decryptStableSyncData(
				encryptedBlob: encrypted,
				wrappedKey: wrapped,
				principalId: cryptoInteropPrincipalID,
				vaultId: "vault-a",
				revision: 1,
				cryptoVersion: VaultCrypto.currentCryptoVersion,
				stableWrappingKey: VaultCrypto.generateAESKey()
			)
		}
	}

	@Test("Unsupported payload versions fail closed")
	func unsupportedPayloadVersionFailsClosed() throws {
		let key = VaultCrypto.generateAESKey()
		let legacy = try VaultCrypto.encrypt(key: key, plaintext: Data("{}".utf8))

		#expect(throws: VaultCrypto.CryptoError.self) {
			_ = try VaultCrypto.decryptPayload(
				key: key,
				encoded: legacy,
				scope: .personal,
				principalId: cryptoInteropPrincipalID,
				vaultId: "vault-a",
				revision: 1,
				cryptoVersion: 4
			)
		}
	}

}
