import CryptoKit
import Foundation
import Testing

@testable import LPMVault

/// Tests that Swift VaultCrypto can decrypt data encrypted by Rust lpm-vault crypto.
/// Test vectors were generated by the Rust crate with known keys.
@Suite("Crypto Interop: Rust ↔ Swift")
struct CryptoInteropTests {

	// ── Test vectors generated by Rust lpm-vault ──

	// Bob's X25519 keypair (generated by Rust)
	let bobPrivateKey = "NqBDUXorl6QdGfKO71T7zs8EwpmJThEj9i6s95x3LnA="
	let bobPublicKey = "bZeps1e2E/303Ch3OcYWHkgsshIU66wRNzrhJbv9/1k="

	// Vault encrypted by Rust (AES-256-GCM)
	let encryptedBlob = "cXlerr85v3ArGvRP:i3xC4zrerSnq6eSXLzPawPlwkwi7i0G7LhFBDtRye3c7LUbaTulbe0RnV5Oc/cqiGOi+YkOKvK8KZlJ+2hzcVzy1LATgFS/6IW0Kq9OXFnb5zaJtXxBPZgFLLBo="

	// AES key wrapped for Bob using X25519 ECIES (by Rust)
	let wrappedKeyForBob = "qdGmOrhXlx0iWRywn5SR2dLyvlcXK47YkSwj6spIqBk=:yzl1/8jJoPcXeVGj:wVhLJAPgsdDNQpHU543nQ6G8Y7RhfKfoEsdFw8q/kCEC6pcA+vNz03Xtosx9hpqc"

	// Expected decrypted JSON
	let expectedJSON = #"{"environments":{"default":{"DB_HOST":"prod.db","API_KEY":"sk-secret-123"}}}"#

	// Personal sync test vectors (token-derived wrapping key)
	let personalBlob = "T/Ns06A5z0dJI/hJ:VVi5NXTbqYO5Oup/21ziWCfIyaquIuZyfD2jgfOj+C2a3BokMWiCVVg951Vj/G/FNMjk+oGr6ySWYCYXMS4epOn+V7EZzPUO4bz995Zdng5bKdaOuWxW0RdulOk="
	let personalWrapped = "mYZqhBMgW/GatTgX:ReGcsQbKFIeTuY5ks7oYdKOJh43lv2jE/3WCiLMQM2+26x2ASi7RTrZU3mAsdFX4"
	let personalToken = "lpm_test_token"

	// MARK: - Personal Sync (Token-based)

	@Test("Swift decrypts Rust personal sync blob")
	func decryptRustPersonalSync() throws {
		let decrypted = try VaultCrypto.decryptFromSync(
			authToken: personalToken,
			encryptedBlob: personalBlob,
			wrappedKey: personalWrapped
		)
		#expect(decrypted == expectedJSON)
	}

	@Test("Rust decrypts Swift personal sync blob (round-trip format)")
	func personalSyncRoundTrip() throws {
		let secrets = expectedJSON
		let (blob, wrapped) = try VaultCrypto.encryptForSync(authToken: personalToken, secretsJSON: secrets)
		let decrypted = try VaultCrypto.decryptFromSync(authToken: personalToken, encryptedBlob: blob, wrappedKey: wrapped)
		#expect(decrypted == secrets)
	}

	// MARK: - Org Sync (X25519 ECIES)

	@Test("Swift unwraps Rust X25519-wrapped key and decrypts vault")
	func unwrapRustX25519Key() throws {
		let privKeyData = Data(base64Encoded: bobPrivateKey)!

		// Unwrap the AES key using Bob's private key
		let aesKey = try VaultCrypto.unwrapKeyFromSender(wrapped: wrappedKeyForBob, privateKey: privKeyData)

		// Decrypt the vault blob
		let plaintext = try VaultCrypto.decrypt(key: aesKey, encoded: encryptedBlob)
		let json = String(data: plaintext, encoding: .utf8)!

		#expect(json == expectedJSON)
	}

	@Test("Swift wraps key, Swift unwraps — round-trip")
	func swiftX25519RoundTrip() throws {
		let (privData, pubData) = VaultCrypto.generateX25519Keypair()
		let aesKey = VaultCrypto.generateAESKey()

		let wrapped = try VaultCrypto.wrapKeyForRecipient(aesKey: aesKey, recipientPublicKey: pubData)
		let unwrapped = try VaultCrypto.unwrapKeyFromSender(wrapped: wrapped, privateKey: privData)

		// Compare key bytes
		let originalBytes = aesKey.withUnsafeBytes { Data($0) }
		let unwrappedBytes = unwrapped.withUnsafeBytes { Data($0) }
		#expect(originalBytes == unwrappedBytes)
	}

	@Test("Wrong private key cannot unwrap")
	func wrongKeyFails() throws {
		let (_, otherPub) = VaultCrypto.generateX25519Keypair()
		let (wrongPriv, _) = VaultCrypto.generateX25519Keypair()
		let aesKey = VaultCrypto.generateAESKey()

		let wrapped = try VaultCrypto.wrapKeyForRecipient(aesKey: aesKey, recipientPublicKey: otherPub)
		#expect(throws: (any Error).self) {
			_ = try VaultCrypto.unwrapKeyFromSender(wrapped: wrapped, privateKey: wrongPriv)
		}
	}

	@Test("Cross-user: Swift encrypts for Rust-generated public key")
	func swiftEncryptsForRustKey() throws {
		let bobPubData = Data(base64Encoded: bobPublicKey)!
		let bobPrivData = Data(base64Encoded: bobPrivateKey)!

		// Swift encrypts a vault and wraps for Bob (Rust-generated key)
		let secrets = #"{"test":"swift-to-rust"}"#
		let aesKey = VaultCrypto.generateAESKey()
		let blob = try VaultCrypto.encrypt(key: aesKey, plaintext: Data(secrets.utf8))
		let wrapped = try VaultCrypto.wrapKeyForRecipient(aesKey: aesKey, recipientPublicKey: bobPubData)

		// Bob unwraps with his Rust-generated private key
		let unwrappedKey = try VaultCrypto.unwrapKeyFromSender(wrapped: wrapped, privateKey: bobPrivData)
		let decrypted = try VaultCrypto.decrypt(key: unwrappedKey, encoded: blob)
		let json = String(data: decrypted, encoding: .utf8)!

		#expect(json == secrets)
	}

	@Test("Public key derivation matches between Swift and Rust")
	func publicKeyDerivation() throws {
		let privData = Data(base64Encoded: bobPrivateKey)!
		let expectedPub = Data(base64Encoded: bobPublicKey)!

		let derivedPub = try VaultCrypto.x25519PublicFromPrivate(privData)
		#expect(derivedPub == expectedPub)
	}

	@Test("Different ephemeral key each wrap")
	func differentEphemeralEachTime() throws {
		let (_, pubData) = VaultCrypto.generateX25519Keypair()
		let aesKey = VaultCrypto.generateAESKey()

		let a = try VaultCrypto.wrapKeyForRecipient(aesKey: aesKey, recipientPublicKey: pubData)
		let b = try VaultCrypto.wrapKeyForRecipient(aesKey: aesKey, recipientPublicKey: pubData)
		#expect(a != b)
	}

	@Test("Protocol v2 AAD matches the cross-language organization vector")
	func protocolV2AADInteropVector() throws {
		let aad = try VaultCrypto.syncAssociatedData(
			scope: .organization(slug: "acme"),
			vaultId: "vault-123",
			cryptoVersion: 2
		)

		#expect(aad.map { String(format: "%02x", $0) }.joined()
			== "6c706d2d7661756c742d73796e63000000000202000000097661756c742d3132330000000461636d65")
	}

	@Test("Protocol v2 rejects a payload copied to another vault ID")
	func protocolV2RejectsCrossVaultSubstitution() throws {
		let key = VaultCrypto.generateAESKey()
		let encrypted = try VaultCrypto.encryptPayload(
			key: key,
			plaintext: Data(#"{"TOKEN":"secret"}"#.utf8),
			scope: .personal,
			vaultId: "vault-a"
		)

		#expect(throws: (any Error).self) {
			_ = try VaultCrypto.decryptPayload(
				key: key,
				encoded: encrypted,
				scope: .personal,
				vaultId: "vault-b",
				cryptoVersion: 2
			)
		}
	}

	@Test("Unsupported payload versions fail closed")
	func unsupportedPayloadVersionFailsClosed() throws {
		let key = VaultCrypto.generateAESKey()
		let legacy = try VaultCrypto.encrypt(key: key, plaintext: Data("{}".utf8))

		#expect(throws: VaultCrypto.CryptoError.self) {
			_ = try VaultCrypto.decryptPayload(
				key: key,
				encoded: legacy,
				scope: .personal,
				vaultId: "vault-a",
				cryptoVersion: 3
			)
		}
	}
}
